maintainer       "YOUR_COMPANY_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures cloudbuilder"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"

depends "apt", ">= 1.4.4"
depends "yum", ">= 0.5.0"
depends "erlang", ">= 0.9"
depends "openssl"
depends "build-essential"
depends "database"
depends "glance"
depends "quantum"
depends "keystone"
depends "mysql"
depends "openstack-common", ">= 0.1.7"
depends "nova"
depends "rabbitmq"
depends "selinux"
depends "sysctl"
depends "yum"
depends "python"
